add:button and input
mithya-team/master-components pull request #2
Opened 2024-06-06 08:16 UTC by sanjaykumaryada

2024-06-06 08:55 UTC, aniruddha-mithya requested changes
Please address these comments

2024-06-06 08:55 UTC, aniruddha-mithya commented on packages/master-components/src/lib/core-components/Tooltip/index.css
> +  top: calc(100% *-1);
Why not just -100%?

2024-06-06 08:55 UTC, aniruddha-mithya commented on packages/master-components/src/lib/core-components/Tooltip/index.css
> +  top: calc(100% *-1);
Or even calc(-100% - 10px) for spacing?

2024-06-06 08:55 UTC, aniruddha-mithya commented on packages/master-components/src/lib/core-components/Input/index.tsx
> +        <div className={`${className} cmp-Input_root`}>
Let's not add the `cmp-` prefix

2024-06-06 08:55 UTC, aniruddha-mithya commented on packages/master-components/src/lib/core-components/Tooltip/index.tsx
> +            if (!fitsBottom && fitsTop) return 'top';
!fitsBottom is redundant here. So is !fitsBottom && !fitsTop in the next line and so on.

2024-06-06 08:55 UTC, aniruddha-mithya commented on packages/master-components/src/lib/core-components/Tooltip/index.css
> +/* Absolute positioning */
We can probably get rid of this comment everywhere.

2024-06-06 11:28 UTC, aniruddha-mithya requested changes

2024-06-06 11:28 UTC, aniruddha-mithya commented on packages/master-components/src/lib/core-components/Button/index.tsx
> +	tooltipprops?: TooltipProps;
Make this tooltipProps please.

2024-06-06 11:28 UTC, aniruddha-mithya commented on packages/master-components/src/lib/core-components/Tooltip/index.css
> +  top: calc(-100%);
Why have `calc()` at all?

2024-06-06 11:28 UTC, aniruddha-mithya commented on packages/master-components/src/lib/core-components/Tooltip/index.tsx
> +    }, [placement, tooltipRef])
This is not useful since tooltipRef does not change when the component rerenders. tooltipRef.current changes but not tooltipRef. Even then when tooltipRef.current changes, the component is not rerendered.

2024-06-07 06:24 UTC, sanjaykumaryada commented on packages/master-components/src/lib/core-components/Button/index.tsx
> +	tooltipprops?: TooltipProps;
this is done knownigly as browser was giving error on toolTipProps and tooltipProps both

2024-06-11 05:01 UTC, merged